# NumPy Library

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.



## Installing NumPy

In [ ]:
!pip install numpy

## Importing the NumPy

In [1]:
import numpy as np # np is abbreviation

## Create an array

In [2]:
# 0D
myArr = np.array([1])
print(myArr)

[1]


In [3]:
# 1D
myArr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(myArr)

[1 2 3 4 5 6 7 8]


In [4]:
# 2D
myArr = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])

print(myArr)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
# 3D
myArr = np.array([[[1, 2, 3, 4],
                   [5, 6, 7, 8]],
                  [[1, 2, 3, 4],
                   [5, 6, 7, 8]]])

print(myArr)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]


### Zeros array

In [6]:
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [9]:
a = np.zeros([5, 5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Ones array

In [10]:
b = np.ones(5)
print(b)

[1. 1. 1. 1. 1.]


In [11]:
b = np.ones([5, 5])
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### Empty array

In [12]:
c = np.empty(5)
print(c)

array([1., 1., 1., 1., 1.])

In [13]:
c = np.empty([5, 5])
print(c)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### Array range

In [16]:
d = np.arange(1, 11)
print(d)

[ 1  2  3  4  5  6  7  8  9 10]


In [17]:
d = np.arange(1, 11, 2)
print(d)

[1 3 5 7 9]


### Linearly specified 

In [18]:
e = np.linspace(0, 20)
print(e)

[ 0.          0.40816327  0.81632653  1.2244898   1.63265306  2.04081633
  2.44897959  2.85714286  3.26530612  3.67346939  4.08163265  4.48979592
  4.89795918  5.30612245  5.71428571  6.12244898  6.53061224  6.93877551
  7.34693878  7.75510204  8.16326531  8.57142857  8.97959184  9.3877551
  9.79591837 10.20408163 10.6122449  11.02040816 11.42857143 11.83673469
 12.24489796 12.65306122 13.06122449 13.46938776 13.87755102 14.28571429
 14.69387755 15.10204082 15.51020408 15.91836735 16.32653061 16.73469388
 17.14285714 17.55102041 17.95918367 18.36734694 18.7755102  19.18367347
 19.59183673 20.        ]


In [19]:
e = np.linspace(0, 20, 5)
print(e)

[ 0.  5. 10. 15. 20.]


## Adding, removing, and sorting elements

In [21]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

### Sort

In [22]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

### Concatenate

In [24]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [25]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

## Shape and size of an array

In [26]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

### Number of dimensions 

In [27]:
array_example.ndim

3

### Total number of elements

In [28]:
array_example.size

24

Shape of an array

In [29]:
array_example.shape

(3, 2, 4)